[package]
name = "damock"
readme = "README.md"

authors.workspace = true
description.workspace = true
edition.workspace = true
exclude.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
damock-macros.workspace = true

[dev-dependencies]
trybuild = "1.0"
